version: '3'
services:
  # PHP
  php:
    container_name: harmony_php
    build: ./.docker/php
    expose:
      - 9000
    volumes:
      - .:/usr/src/harmony
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa # Share local machine SSH key to docker
    links:
      - mariadb
      - mongodb
    working_dir: /usr/src/harmony
    networks:
      - harmony
  # Nginx
  nginx:
    container_name: harmony_nginx
    image: nginx
    ports:
      - 8080:80
    links:
      - php
    volumes:
      - .:/usr/src/harmony
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /usr/src/harmony
    networks:
      - harmony
  # MariaDB
  mariadb:
    container_name: harmony_db
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    networks:
      - harmony

  # MongoDB
  mongodb:
    image: mongo
    container_name: harmony_mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
    networks:
      - harmony

networks:
  harmony:
    driver: bridge
volumes:
  data:
    driver: local